// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJKlWp5KvcxbAnqCNx1iOa1E-2866HGg',
    appId: '1:527856994660:web:3bdbd3bdee3b1d4f601271',
    messagingSenderId: '527856994660',
    projectId: 'studybudtest',
    authDomain: 'studybudtest.firebaseapp.com',
    storageBucket: 'studybudtest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkuU3TP9-j-ep-sPUbuDCWBQO_ePf7q5Q',
    appId: '1:527856994660:android:95ccb094b3f05922601271',
    messagingSenderId: '527856994660',
    projectId: 'studybudtest',
    storageBucket: 'studybudtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCzyGghL5dLVqWMgDZi2TyzyxSkgLvog4',
    appId: '1:527856994660:ios:22cd3318057ec547601271',
    messagingSenderId: '527856994660',
    projectId: 'studybudtest',
    storageBucket: 'studybudtest.appspot.com',
    iosClientId: '527856994660-385p6v0qjpd270c916nib115prcnaec6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCzyGghL5dLVqWMgDZi2TyzyxSkgLvog4',
    appId: '1:527856994660:ios:e1cc8ba1465b7239601271',
    messagingSenderId: '527856994660',
    projectId: 'studybudtest',
    storageBucket: 'studybudtest.appspot.com',
    iosClientId: '527856994660-vl51f1hppelpfueog7j9b3k38orjn09q.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBud.RunnerTests',
  );
}
